
#name: $(GitVersion_NuGetVersion)
name: $(VersionNumberMajor).$(VersionNumberMinor).$(VersionNumberBuild)$(Rev:.rrrr)

resources:
- repo: self
  fetchDepth: 30

pool:
  name: DCT
  demands:
  - IsBuildServer
  - msbuild
  - visualstudio
  - vstest

variables:
  Parameters.solution: '**\*.sln'
  Parameters.nugetFeedName: 'dct-pkg'
  VersionNumberMajor: '1'
  VersionNumberMinor: '0'
  VersionNumberBuild: '2'
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  group: 'CodeSign KV'
 

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  enabled: false
  inputs:
    updateAssemblyInfo: true
    preferBundledVersion: false

- task: VersionAssemblies@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    VersionNumber: '$(Build.BuildNumber)'
    InjectVersion: False
    FilenamePattern: 'AssemblyInfo.*'
    OutputVersion: 'OutputedVersion'

- task: PowerShell@1
  displayName: 'Dissplay Variables'
  enabled: true
  inputs:
    scriptType: inlineScript
    inlineScript: |
     $var = (gci env:*).GetEnumerator() | Sort-Object Name
     $out = ""
     Foreach ($v in $var) 
     {
     write-output "Name: $($v.Name)  | Value : $($v.Value)"
     }

- task: PowerShell@1
  displayName: 'Dissplay Variables a'
  enabled: true
  inputs:
    scriptType: inlineScript
    inlineScript: |
     write-output "Code Sign Pwd : $env:CODESIGNPWDDFE"

- task: PowerShell@1
  displayName: 'Dissplay Variables b'
  enabled: true
  inputs:
    scriptType: inlineScript
    inlineScript: |
     write-output "Code Sign PFX : $env:CodeSignCertificatePFX"


- task: NuGetToolInstaller@0
  displayName: 'Use NuGet >=4.7.0'
  inputs:
    versionSpec: '>=4.7.0'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'
    vstsFeed: '$(Parameters.nugetFeedName)'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '$(Parameters.solution)'
    msbuildArgs: '/p:version=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true


- task: CopyFiles@2
  displayName: 'Copy Nuget Interface Packages Files - Artifact NugetInterface Directory'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)\src'
    Contents: |
     **\*$(BuildConfiguration)*\*Interface.nupkg
     !**\packages\**
     !**\bin\x64\**
    TargetFolder: '$(build.artifactstagingdirectory)\Nuget\Interface'
    CleanTargetFolder: true
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy NugetPackages Files - Artifact NugetPackages Directory'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)\src'
    Contents: |
     **\*$(BuildConfiguration)*\*.nupkg
     !**\packages\**
     !**\bin\x64\**
    TargetFolder: '$(build.artifactstagingdirectory)\Nuget\Packages'
    CleanTargetFolder: true
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy Application File to Artifact Folder'
  inputs:
    SourceFolder: 'src/ESFA.DC.ILR.Desktop.WPF\bin\$(BuildConfiguration)'  
    Contents: '**\!(*.pdb)'
    TargetFolder: '$(build.ArtifactStagingDirectory)\DesktopApplication'

- task: CopyFiles@2
  displayName: 'Copy Published Storage Account Files - Artifact StorageAccount Directory'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)\StorageAccount'
    Contents: |
      **\*
    TargetFolder: '$(build.artifactstagingdirectory)\StorageAccount'
    CleanTargetFolder: true
    flattenFolders: false

- task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
  displayName: 'Tokenization: Transform Application config file'
  enabled: false
  inputs:
    SourcePath: '$(build.ArtifactStagingDirectory)\DesktopApplication'
    TargetFileNames: '*.exe.config'
    RequireVariable: false

- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    runInParallel: true
    codeCoverageEnabled: true
    diagnosticsEnabled: true

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  enabled: false
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: NugetPackages'
  enabled: true
  inputs:
    ArtifactName: NugetPackages
    PathtoPublish: '$(build.artifactstagingdirectory)\Nuget'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: DesktopApplication'
  enabled: true
  inputs:
    ArtifactName: DesktopApplication
    PathtoPublish: '$(build.artifactstagingdirectory)\DesktopApplication'


#********************************************************************************
# CodeSign Script body
# Application Signing execution begins here
#********************************************************************************
- task: PowerShell@2
  displayName: 'CodeSign DfE DesktopApplications inLine and inBuild'
  enabled: true  
  env:
    CodeSignPwdDfE: $(CodeSignPwdDfE)
  inputs:
    filePath: 'C:\Users\BuildAdmin\Desktop\CodeSign\DFE_Code_Signing.ps1'
#********************************************************************************
#Application Signing execution ends here
#********************************************************************************
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: StoraegAccount Display Files'
  enabled: true
  inputs:
    ArtifactName: StorageAccount
    PathtoPublish: '$(build.artifactstagingdirectory)\StorageAccount'


