
name: $(GitVersion_NuGetVersion)
#name: $(VersionNumberMajor).$(VersionNumberMinor).$(VersionNumberBuild)$(Rev:.rrrr)

resources:
- repo: self
  fetchDepth: 30

pool:
  name: DCT
  demands:
  - IsBuildServer
  - msbuild
  - visualstudio
  - vstest

variables:
  VersionNumberMajor: '1'
  VersionNumberMinor: '2'
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  Parameters.solution: '**\*.sln'
  Parameters.nugetFeedName: 'dct-pkg'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  enabled: true
  inputs:
    updateAssemblyInfo: true
    preferBundledVersion: false

- task: PowerShell@1
  displayName: 'Dissplay Variables'
  enabled: true
  inputs:
    scriptType: inlineScript
    inlineScript: |
     $var = (gci env:*).GetEnumerator() | Sort-Object Name
     $out = ""
     Foreach ($v in $var) 
     {
     write-output "Name: $($v.Name)  | Value : $($v.Value)"
     }


- task: NuGetToolInstaller@0
  displayName: 'Use NuGet >=4.7.0'
  inputs:
    versionSpec: '>=4.7.0'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'
    vstsFeed: '$(Parameters.nugetFeedName)'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '$(Parameters.solution)'
    msbuildArgs: '/p:version=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true

- task: CopyFiles@2
  displayName: 'Copy NuGet Packages : Artifact NuGet Packages Directory'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **\*.nupkg
     !**\*Interface*.nupkg
     !**\packages\**\*.nupkg
    TargetFolder: '$(build.artifactstagingdirectory)\NuGet'
    CleanTargetFolder: true
    flattenFolders: true
    
- task: CopyFiles@2
  displayName: 'Copy NuGet Packages : Artifact NuGet Interface Packages Directory'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **\*Interface*.nupkg
     !**\packages\**\*.nupkg
    TargetFolder: '$(build.artifactstagingdirectory)\NuGet Interface'
    CleanTargetFolder: true
    flattenFolders: true

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  enabled: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Application File to Artifact Folder'
  inputs:
    SourceFolder: 'src/ESFA.DC.ILR.Desktop.WPF\bin\$(BuildConfiguration)'  
    Contents: '**\!(*.pdb)'
    TargetFolder: '$(build.ArtifactStagingDirectory)\DesktopApplication'
    

- task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
  displayName: 'Tokenization: Transform Application config file'
  inputs:
    SourcePath: '$(build.ArtifactStagingDirectory)\DesktopApplication'
    TargetFileNames: '*.exe.config'
    RequireVariable: false

  ## Create Zip File for Deployment     
- task: ArchiveFiles@2
  enabled: false
  displayName: 'Package WebJobs for Website'
  inputs:
    rootFolderOrFile: '$(build.BinariesDirectory)\tmp'
    includeRootFolder: false
    archiveFile: '$(build.ArtifactStagingDirectory)\DC-ILR-1920-Desktop.$(Build.BuildNumber).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
